USE knowledge_base;

ALTER TABLE `users` COMMENT = '用户表';
ALTER TABLE `users`
  MODIFY COLUMN `user_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户主键 ID',
  MODIFY COLUMN `username` VARCHAR(64) NOT NULL COMMENT '登录用户名',
  MODIFY COLUMN `password_hash` VARCHAR(255) NOT NULL COMMENT '密码哈希',
  MODIFY COLUMN `role` VARCHAR(20) NOT NULL DEFAULT 'USER' COMMENT '兼容旧逻辑的主角色标记',
  MODIFY COLUMN `display_name` VARCHAR(100) DEFAULT NULL COMMENT '显示名称',
  MODIFY COLUMN `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  MODIFY COLUMN `department` VARCHAR(100) DEFAULT NULL COMMENT '所属部门',
  MODIFY COLUMN `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  MODIFY COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN `last_login` TIMESTAMP NULL DEFAULT NULL COMMENT '最后登录时间';

ALTER TABLE `roles` COMMENT = '角色定义表';
ALTER TABLE `roles`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '角色主键 ID',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '角色编码',
  MODIFY COLUMN `name` VARCHAR(100) NOT NULL COMMENT '角色名称',
  MODIFY COLUMN `description` VARCHAR(255) DEFAULT NULL COMMENT '角色说明',
  MODIFY COLUMN `system_role` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否系统内置角色',
  MODIFY COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE `permissions` COMMENT = '权限定义表';
ALTER TABLE `permissions`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '权限主键 ID',
  MODIFY COLUMN `code` VARCHAR(100) NOT NULL COMMENT '权限编码',
  MODIFY COLUMN `name` VARCHAR(100) NOT NULL COMMENT '权限名称',
  MODIFY COLUMN `module` VARCHAR(64) NOT NULL COMMENT '所属模块',
  MODIFY COLUMN `description` VARCHAR(255) DEFAULT NULL COMMENT '权限说明',
  MODIFY COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE `role_permissions` COMMENT = '角色权限关联表';
ALTER TABLE `role_permissions`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '关联主键 ID',
  MODIFY COLUMN `role_id` BIGINT NOT NULL COMMENT '角色 ID',
  MODIFY COLUMN `permission_id` BIGINT NOT NULL COMMENT '权限 ID',
  MODIFY COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE `user_roles` COMMENT = '用户角色关联表';
ALTER TABLE `user_roles`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '关联主键 ID',
  MODIFY COLUMN `user_id` BIGINT NOT NULL COMMENT '用户 ID',
  MODIFY COLUMN `role_id` BIGINT NOT NULL COMMENT '角色 ID',
  MODIFY COLUMN `assigned_by` BIGINT DEFAULT NULL COMMENT '分配人用户 ID',
  MODIFY COLUMN `assigned_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '分配时间';

ALTER TABLE `knowledge_bases` COMMENT = '知识库表';
ALTER TABLE `knowledge_bases`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '知识库主键 ID',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '知识库编码',
  MODIFY COLUMN `name` VARCHAR(100) NOT NULL COMMENT '知识库名称',
  MODIFY COLUMN `description` TEXT DEFAULT NULL COMMENT '知识库描述',
  MODIFY COLUMN `visibility` VARCHAR(20) NOT NULL DEFAULT 'PRIVATE' COMMENT '可见性',
  MODIFY COLUMN `owner_user_id` BIGINT DEFAULT NULL COMMENT '负责人用户 ID',
  MODIFY COLUMN `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  MODIFY COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE `knowledge_categories` COMMENT = '知识库分类表';
ALTER TABLE `knowledge_categories`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '分类主键 ID',
  MODIFY COLUMN `knowledge_base_id` BIGINT NOT NULL COMMENT '所属知识库 ID',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '分类编码',
  MODIFY COLUMN `name` VARCHAR(100) NOT NULL COMMENT '分类名称',
  MODIFY COLUMN `description` VARCHAR(255) DEFAULT NULL COMMENT '分类描述',
  MODIFY COLUMN `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序值',
  MODIFY COLUMN `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  MODIFY COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE `documents` COMMENT = '文档表';
ALTER TABLE `documents`
  MODIFY COLUMN `doc_id` VARCHAR(64) NOT NULL COMMENT '文档主键 ID',
  MODIFY COLUMN `knowledge_base_id` BIGINT DEFAULT NULL COMMENT '所属知识库 ID',
  MODIFY COLUMN `category_id` BIGINT DEFAULT NULL COMMENT '所属分类 ID',
  MODIFY COLUMN `uploaded_by` BIGINT DEFAULT NULL COMMENT '上传人用户 ID',
  MODIFY COLUMN `reviewed_by` BIGINT DEFAULT NULL COMMENT '审核人用户 ID',
  MODIFY COLUMN `original_filename` VARCHAR(255) NOT NULL COMMENT '原始文件名',
  MODIFY COLUMN `stored_path` VARCHAR(512) NOT NULL COMMENT '存储路径',
  MODIFY COLUMN `display_name` VARCHAR(255) DEFAULT NULL COMMENT '展示名称',
  MODIFY COLUMN `description` TEXT DEFAULT NULL COMMENT '文档描述',
  MODIFY COLUMN `file_size` BIGINT DEFAULT 0 COMMENT '文件大小（字节）',
  MODIFY COLUMN `file_type` VARCHAR(50) DEFAULT NULL COMMENT '文件类型',
  MODIFY COLUMN `checksum` VARCHAR(64) DEFAULT NULL COMMENT '文件校验值',
  MODIFY COLUMN `machine_type` VARCHAR(100) DEFAULT NULL COMMENT '设备型号',
  MODIFY COLUMN `metadata_json` TEXT DEFAULT NULL COMMENT '扩展元数据 JSON',
  MODIFY COLUMN `status` VARCHAR(50) NOT NULL COMMENT '文档状态',
  MODIFY COLUMN `hidden` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否隐藏',
  MODIFY COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN `reviewed_at` TIMESTAMP NULL DEFAULT NULL COMMENT '审核时间',
  MODIFY COLUMN `error_message` TEXT DEFAULT NULL COMMENT '错误信息';

ALTER TABLE `tasks` COMMENT = '异步任务表';
ALTER TABLE `tasks`
  MODIFY COLUMN `task_id` VARCHAR(64) NOT NULL COMMENT '任务主键 ID',
  MODIFY COLUMN `target_id` VARCHAR(64) DEFAULT NULL COMMENT '目标对象 ID',
  MODIFY COLUMN `type` VARCHAR(50) NOT NULL COMMENT '任务类型',
  MODIFY COLUMN `status` VARCHAR(50) NOT NULL COMMENT '任务状态',
  MODIFY COLUMN `progress` INT DEFAULT 0 COMMENT '任务进度',
  MODIFY COLUMN `error_message` TEXT DEFAULT NULL COMMENT '任务错误信息',
  MODIFY COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN `started_at` TIMESTAMP NULL DEFAULT NULL COMMENT '开始时间',
  MODIFY COLUMN `finished_at` TIMESTAMP NULL DEFAULT NULL COMMENT '结束时间';

ALTER TABLE `document_processing_event` COMMENT = '文档处理事件表';
ALTER TABLE `document_processing_event`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '事件主键 ID',
  MODIFY COLUMN `doc_id` VARCHAR(64) NOT NULL COMMENT '文档 ID',
  MODIFY COLUMN `file_type` VARCHAR(50) NOT NULL COMMENT '文件类型',
  MODIFY COLUMN `step` VARCHAR(50) NOT NULL COMMENT '处理步骤',
  MODIFY COLUMN `status` VARCHAR(20) NOT NULL COMMENT '步骤状态',
  MODIFY COLUMN `message` VARCHAR(255) DEFAULT NULL COMMENT '步骤说明',
  MODIFY COLUMN `payload_json` TEXT DEFAULT NULL COMMENT '步骤载荷 JSON',
  MODIFY COLUMN `started_at` TIMESTAMP NULL DEFAULT NULL COMMENT '步骤开始时间',
  MODIFY COLUMN `finished_at` TIMESTAMP NULL DEFAULT NULL COMMENT '步骤结束时间',
  MODIFY COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间';

ALTER TABLE `search_logs` COMMENT = '检索日志表';
ALTER TABLE `search_logs`
  MODIFY COLUMN `log_id` VARCHAR(64) NOT NULL COMMENT '日志主键 ID',
  MODIFY COLUMN `user_id` BIGINT DEFAULT NULL COMMENT '检索用户 ID',
  MODIFY COLUMN `query_text` TEXT NOT NULL COMMENT '检索问题',
  MODIFY COLUMN `search_mode` VARCHAR(50) NOT NULL COMMENT '检索模式',
  MODIFY COLUMN `has_rerank` TINYINT(1) DEFAULT 0 COMMENT '是否启用重排',
  MODIFY COLUMN `result_count` INT DEFAULT 0 COMMENT '结果数量',
  MODIFY COLUMN `total_latency` INT DEFAULT 0 COMMENT '总耗时毫秒',
  MODIFY COLUMN `es_latency` INT DEFAULT 0 COMMENT '检索阶段耗时毫秒',
  MODIFY COLUMN `model_latency` INT DEFAULT 0 COMMENT '模型阶段耗时毫秒',
  MODIFY COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE `feedback` COMMENT = '检索反馈表';
ALTER TABLE `feedback`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '反馈主键 ID',
  MODIFY COLUMN `search_id` VARCHAR(64) NOT NULL COMMENT '检索日志 ID',
  MODIFY COLUMN `doc_id` VARCHAR(64) DEFAULT NULL COMMENT '文档 ID',
  MODIFY COLUMN `chunk_id` VARCHAR(128) DEFAULT NULL COMMENT '切片 ID',
  MODIFY COLUMN `rank_position` INT DEFAULT NULL COMMENT '原始排序位置',
  MODIFY COLUMN `is_relevant` TINYINT(1) NOT NULL COMMENT '是否相关',
  MODIFY COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE `qa_logs` COMMENT = '问答日志表';
ALTER TABLE `qa_logs`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '日志主键 ID',
  MODIFY COLUMN `query` TEXT NOT NULL COMMENT '问题内容',
  MODIFY COLUMN `answer` TEXT DEFAULT NULL COMMENT '回答内容',
  MODIFY COLUMN `duration_ms` BIGINT NOT NULL COMMENT '耗时毫秒',
  MODIFY COLUMN `source_count` INT NOT NULL COMMENT '引用来源数量',
  MODIFY COLUMN `timestamp` DATETIME(6) NOT NULL COMMENT '记录时间';

ALTER TABLE `permission_requests` COMMENT = '权限申请表';
ALTER TABLE `permission_requests`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '申请主键 ID',
  MODIFY COLUMN `user_id` BIGINT NOT NULL COMMENT '申请用户 ID',
  MODIFY COLUMN `permission_code` VARCHAR(100) NOT NULL COMMENT '申请权限编码',
  MODIFY COLUMN `resource_type` VARCHAR(50) NOT NULL COMMENT '资源类型',
  MODIFY COLUMN `resource_id` VARCHAR(64) DEFAULT NULL COMMENT '资源 ID',
  MODIFY COLUMN `reason` VARCHAR(500) DEFAULT NULL COMMENT '申请原因',
  MODIFY COLUMN `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '申请状态',
  MODIFY COLUMN `reviewer_id` BIGINT DEFAULT NULL COMMENT '审批人用户 ID',
  MODIFY COLUMN `review_comment` VARCHAR(500) DEFAULT NULL COMMENT '审批意见',
  MODIFY COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '申请时间',
  MODIFY COLUMN `reviewed_at` TIMESTAMP NULL DEFAULT NULL COMMENT '审批时间';

ALTER TABLE `user_permission_grants` COMMENT = '用户授权表';
ALTER TABLE `user_permission_grants`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '授权主键 ID',
  MODIFY COLUMN `user_id` BIGINT NOT NULL COMMENT '被授权用户 ID',
  MODIFY COLUMN `permission_code` VARCHAR(100) NOT NULL COMMENT '授权权限编码',
  MODIFY COLUMN `resource_type` VARCHAR(50) NOT NULL COMMENT '资源类型',
  MODIFY COLUMN `resource_id` VARCHAR(64) DEFAULT NULL COMMENT '资源 ID',
  MODIFY COLUMN `granted_by` BIGINT DEFAULT NULL COMMENT '授权人用户 ID',
  MODIFY COLUMN `source_request_id` BIGINT DEFAULT NULL COMMENT '来源申请 ID',
  MODIFY COLUMN `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '授权状态',
  MODIFY COLUMN `effective_from` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '生效开始时间',
  MODIFY COLUMN `effective_to` TIMESTAMP NULL DEFAULT NULL COMMENT '生效结束时间',
  MODIFY COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE `audit_logs` COMMENT = '审计日志表';
ALTER TABLE `audit_logs`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '审计主键 ID',
  MODIFY COLUMN `operator_user_id` BIGINT DEFAULT NULL COMMENT '操作人用户 ID',
  MODIFY COLUMN `action` VARCHAR(100) NOT NULL COMMENT '操作动作',
  MODIFY COLUMN `target_type` VARCHAR(50) NOT NULL COMMENT '目标类型',
  MODIFY COLUMN `target_id` VARCHAR(64) DEFAULT NULL COMMENT '目标 ID',
  MODIFY COLUMN `details_json` TEXT DEFAULT NULL COMMENT '详细内容 JSON',
  MODIFY COLUMN `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
